# Generated by Django 5.2.5 on 2025-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="token_prefix",
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
