# Generated by Django 5.2.5 on 2025-08-11 17:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("service", models.CharField(default="core.image_solve", max_length=100)),
                ("request_ts", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("duration_ms", models.IntegerField()),
                ("request_bytes", models.IntegerField()),
                ("response_bytes", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")], max_length=10
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("request_id", models.UUIDField(db_index=True)),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="customers.apitoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "request_logs",
                "ordering": ["-request_ts"],
                "indexes": [
                    models.Index(
                        fields=["user", "-request_ts"], name="request_log_user_id_cc57af_idx"
                    ),
                    models.Index(fields=["request_ts"], name="request_log_request_f0181f_idx"),
                    models.Index(fields=["request_id"], name="request_log_request_85729c_idx"),
                ],
            },
        ),
    ]
