# Generated by Django 5.2.5 on 2025-08-13 13:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField(db_index=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("total_cost_cents", models.IntegerField(default=0)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("paid_amount_cents", models.IntegerField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="External invoice or payment reference number",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("payment_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_periods",
                "ordering": ["-period_start"],
            },
        ),
        migrations.AddField(
            model_name="requestlog",
            name="billing_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="usage.billingperiod",
            ),
        ),
        migrations.AddIndex(
            model_name="billingperiod",
            index=models.Index(
                fields=["user", "is_current"], name="billing_per_user_id_4faee3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingperiod",
            index=models.Index(
                fields=["period_start", "period_end"], name="billing_per_period__b74a16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingperiod",
            index=models.Index(fields=["payment_status"], name="billing_per_payment_4fec8e_idx"),
        ),
        migrations.AddIndex(
            model_name="billingperiod",
            index=models.Index(
                fields=["user", "payment_status"], name="billing_per_user_id_72765b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billingperiod",
            unique_together={("user", "period_start")},
        ),
    ]
