# Generated by Django 5.2.5 on 2025-08-24 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage", "0002_billingperiod_requestlog_billing_period_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("image_data", models.BinaryField()),
                ("mime_type", models.CharField(default="image/jpeg", max_length=50)),
                ("file_size", models.IntegerField()),
                ("image_hash", models.CharField(db_index=True, max_length=64)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_image",
                        to="usage.requestlog",
                    ),
                ),
            ],
            options={
                "db_table": "request_images",
                "indexes": [
                    models.Index(fields=["image_hash"], name="request_ima_image_h_e72f4d_idx"),
                    models.Index(fields=["created_at"], name="request_ima_created_393667_idx"),
                ],
            },
        ),
    ]
