# Generated by Django 5.2.5 on 2025-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cost_per_request_cents", models.IntegerField(default=100)),
                ("openai_model", models.CharField(default="gpt-vision", max_length=100)),
                ("openai_timeout_s", models.IntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
                "db_table": "settings",
            },
        ),
    ]
