# Generated by Django 5.2.5 on 2025-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="app_domain",
            field=models.URLField(
                blank=True,
                help_text="Frontend application domain for email verification links (e.g., https://app.example.com). If empty, uses the backend domain.",
                max_length=255,
                verbose_name="Application Domain",
            ),
        ),
    ]
