# Generated by Django 5.2.5 on 2025-08-28 19:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_app_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="app_domain",
            field=models.URLField(
                blank=True,
                help_text="Frontend application domain for email verification links (e.g., https://app.example.com). If empty, uses the backend domain.",
                max_length=255,
                validators=[core.models.FlexibleURLValidator()],
                verbose_name="Application Domain",
            ),
        ),
    ]
