name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build application
        working-directory: frontend
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_MAX_VERIFICATION_ATTEMPTS: ${{ vars.VITE_MAX_VERIFICATION_ATTEMPTS }}
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: frontend
          command: deploy

      - name: Create deployment summary
        if: success()
        run: |
          echo "## Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Frontend has been deployed to Cloudflare Pages" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Details" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- Time: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY

  # preview:
  #   runs-on: ubuntu-latest
  #   name: Deploy Preview to Cloudflare Pages
  #   if: github.event_name == 'pull_request'
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #         cache-dependency-path: frontend/package-lock.json
  #
  #     - name: Install dependencies
  #       working-directory: frontend
  #       run: npm ci
  #
  #     - name: Build application
  #       working-directory: frontend
  #       env:
  #         VITE_API_URL: ${{ secrets.VITE_API_URL_PREVIEW }}
  #         VITE_MAX_VERIFICATION_ATTEMPTS: ${{ secrets.VITE_MAX_VERIFICATION_ATTEMPTS }}
  #       run: npm run build
  #
  #     - name: Deploy Preview to Cloudflare Pages
  #       uses: cloudflare/wrangler-action@v3
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         workingDirectory: frontend
  #         command: pages deploy dist --project-name=trc-platform --branch=preview-${{ github.event.pull_request.number }}
  #
  #     - name: Add preview URL comment
  #       uses: actions/github-script@v7
  #       with:
  #         script: |
  #           const comment = `### Preview Deployment Ready
  #
  #           Your preview is being deployed to Cloudflare Pages.
  #
  #           Preview URL will be available at: \`https://preview-${context.issue.number}.trc-platform.pages.dev\`
  #
  #           > Note: It may take a few minutes for the deployment to be fully available.`;
  #
  #           github.rest.issues.createComment({
  #             issue_number: context.issue.number,
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             body: comment
  #           });
